"""rename department

Revision ID: 5827bbf08950
Revises: 3e2fbef1ca42
Create Date: 2024-04-07 07:34:30.576436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5827bbf08950'
down_revision = '3e2fbef1ca42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###